# Generated by Django 6.0.6 on 2026-06-17 14:15

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_remove_document_content_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=500, upload_to=documents.models.document_upload_to, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='document',
            name='original_filename',
            field=models.CharField(blank=True, editable=False, max_length=255, verbose_name='Оригинальное имя файла'),
        ),
    ]
